# Generated by Django 3.2 on 2021-05-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxapprover',
            name='dest',
            field=models.ManyToManyField(related_name='fxapprover', to='fxapp.FXDestination'),
        ),
    ]
