# Generated by Django 3.2 on 2021-05-04 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0002_alter_fxapprover_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxtaskspec',
            name='task_status',
            field=models.CharField(choices=[('DRAFTING', 'Drafting'), ('QUEUED', 'Queued up'), ('APPROVED', 'Approved'), ('COPY.2.LIB', 'Copying to Library'), ('GEN.IDX.LIB', 'Updating Index'), ('MOVE.2.ARCH', 'Moving previous issue to Library'), ('COMPLETE', 'Completed')], default='DRAFTING', max_length=12, verbose_name='Task Status'),
        ),
        migrations.CreateModel(
            name='FXSourceFilesSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_spec_kind', models.CharField(choices=[('ONE', '*ONE* File Specified'), ('ALL', '*ALL* Files from the related Source path (top level only)'), ('REC', 'All Files from the related Source path (all top level and all found by *REC*ursing into sub dirs)')], max_length=3, verbose_name='File Spec Kind')),
                ('file_spec_filter', models.CharField(blank=True, default='*.*', max_length=300, verbose_name='File Spec Filter')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='File name')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_file_spec', to='fxapp.fxsource')),
            ],
            options={
                'verbose_name': 'File Source Spec',
                'verbose_name_plural': 'File Source Specs',
            },
        ),
        migrations.CreateModel(
            name='FXApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_userac', models.CharField(max_length=10, verbose_name='Approved by (user account)')),
                ('approval_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date approved')),
                ('task_spec_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='fxapp.fxtaskspec')),
            ],
        ),
        migrations.AddField(
            model_name='fxtaskspec',
            name='file_source_spec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxsourcefilesspec'),
            preserve_default=False,
        ),
    ]
