# Generated by Django 3.2 on 2021-05-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0003_auto_20210504_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxtaskspec',
            name='file_source_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxsourcefilesspec'),
        ),
    ]
