# Generated by Django 3.2 on 2021-05-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0004_alter_fxtaskspec_file_source_spec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxtaskspec',
            old_name='task_status',
            new_name='task_stage',
        ),
    ]
