# Generated by Django 3.2 on 2021-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0005_rename_task_status_fxtaskspec_task_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxtaskspec',
            name='task_status_detail',
            field=models.CharField(blank=True, default='', max_length=5000, verbose_name='Task Status Detail Information'),
        ),
        migrations.AddField(
            model_name='fxtaskspec',
            name='task_status_ok',
            field=models.BooleanField(default=True, verbose_name='Task Status OK'),
        ),
        migrations.AlterField(
            model_name='fxtaskspec',
            name='task_stage',
            field=models.CharField(choices=[('DRAFTING', 'Drafting'), ('QUEUED', 'Queued up'), ('APPROVED', 'Approved'), ('COPY.2.LIB', 'Copying to Library'), ('GEN.IDX.LIB', 'Updating Index'), ('MOVE.2.ARCH', 'Moving previous issue to Library'), ('COMPLETE', 'Completed')], default='DRAFTING', max_length=12, verbose_name='Task Stage'),
        ),
    ]
