# Generated by Django 3.2 on 2021-05-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0007_auto_20210504_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxtaskspec',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxapprover'),
        ),
    ]
