# Generated by Django 3.2 on 2021-05-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0008_alter_fxtaskspec_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxtaskspec',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxapprover'),
        ),
    ]
