# Generated by Django 3.2 on 2021-05-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FXDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_to_move_path', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'File Destination',
                'verbose_name_plural': 'File Destinations',
            },
        ),
        migrations.CreateModel(
            name='FXSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_source', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'File Source',
                'verbose_name_plural': 'File Sources',
            },
        ),
        migrations.CreateModel(
            name='FXTaskSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by_userac', models.CharField(max_length=10)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxdestination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxsource')),
            ],
            options={
                'verbose_name': 'Task Specification',
                'verbose_name_plural': 'Task Specifications',
            },
        ),
        migrations.CreateModel(
            name='FXApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_userac', models.CharField(max_length=10)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='fxapp.fxdestination')),
            ],
            options={
                'verbose_name': 'Approver',
                'verbose_name_plural': 'Approvers',
            },
        ),
    ]
