# Generated by Django 3.2 on 2021-05-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxapprover',
            name='approver_userac',
            field=models.CharField(max_length=10, verbose_name='Approver user account'),
        ),
        migrations.AlterField(
            model_name='fxdestination',
            name='file_to_move_path',
            field=models.CharField(max_length=300, verbose_name='Destination folder'),
        ),
        migrations.AlterField(
            model_name='fxsource',
            name='file_source',
            field=models.CharField(max_length=300, verbose_name='Source Files or Dir'),
        ),
        migrations.AlterField(
            model_name='fxtaskspec',
            name='raised_by_userac',
            field=models.CharField(help_text='User account of the person raising this request', max_length=10, verbose_name='Raised by user'),
        ),
    ]
