# Generated by Django 3.2 on 2021-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0004_auto_20210501_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxtaskspec',
            name='file_source_doc',
        ),
        migrations.AddField(
            model_name='fxtaskspec',
            name='file_source_doc_path',
            field=models.FilePathField(default='tbc', path='E:\\data\\_090_PROJECTS\\_009_CURRENT\\FileWorx\\test_data\\', verbose_name='Path To Doc'),
            preserve_default=False,
        ),
    ]
