# Generated by Django 3.2 on 2021-05-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0005_auto_20210501_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_paths', models.CharField(max_length=300, verbose_name='Doc Source folders')),
            ],
        ),
        migrations.AlterField(
            model_name='fxtaskspec',
            name='file_source_doc_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.fxsource'),
        ),
    ]
