# Generated by Django 3.2 on 2021-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0007_auto_20210501_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxsource',
            name='source_path_friendlyname',
            field=models.CharField(max_length=300, verbose_name='Doc Source folder friendly name'),
        ),
    ]
