# Generated by Django 3.2 on 2021-05-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0008_alter_fxsource_source_path_friendlyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxdestination',
            old_name='file_to_move_path',
            new_name='dest_path',
        ),
        migrations.AddField(
            model_name='fxdestination',
            name='dest_path_friendlyname',
            field=models.CharField(default='tbc', max_length=300, verbose_name='Doc Destination folder friendly name'),
            preserve_default=False,
        ),
    ]
