# Generated by Django 3.2 on 2021-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0009_auto_20210501_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxapprover',
            name='dest',
        ),
        migrations.AddField(
            model_name='fxapprover',
            name='dest',
            field=models.ManyToManyField(related_name='approver', to='fxapp.FXDestination'),
        ),
    ]
