# Generated by Django 3.2 on 2021-05-01 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0010_auto_20210501_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxtaskspec',
            name='raised_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date raised'),
        ),
    ]
