# Generated by Django 3.2 on 2021-05-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0013_alter_fxtaskspec_raised_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fxapprover',
            options={'ordering': ['approver_userac'], 'verbose_name': 'Approver', 'verbose_name_plural': 'Approvers'},
        ),
        migrations.AlterModelOptions(
            name='fxdestination',
            options={'ordering': ['dest_path_friendlyname'], 'verbose_name': 'File Destination', 'verbose_name_plural': 'File Destinations'},
        ),
        migrations.AlterModelOptions(
            name='fxsource',
            options={'ordering': ['source_path_friendlyname'], 'verbose_name': 'Source Folder', 'verbose_name_plural': 'Source Folders'},
        ),
        migrations.AlterModelOptions(
            name='fxtaskspec',
            options={'ordering': ['raised_date'], 'verbose_name': 'Task Specification', 'verbose_name_plural': 'Task Specifications'},
        ),
    ]
